"""Media stage services: yt-dlp metadata/audio download and ffmpeg normalization."""

import asyncio
import subprocess
from concurrent.futures import Executor
from dataclasses import dataclass
from pathlib import Path
from typing import Any
from uuid import uuid4

import yt_dlp


class VideoInfoError(Exception):
    """Raised when video metadata extraction fails."""


class MediaDownloadError(Exception):
    """Raised when audio download/conversion fails."""


@dataclass
class DownloadedAudio:
    """Audio artifact generated by media stage."""

    audio_path: Path
    video_title: str
    expected_duration_seconds: float | None
    actual_duration_seconds: float | None


class MediaService:
    """Thin adapter around yt-dlp + ffmpeg."""

    def __init__(self, *, preferred_codec: str = "m4a"):
        self._preferred_codec = preferred_codec
        self._base_ydl_opts = {
            "format": "bestaudio/best",
            "postprocessors": [
                {
                    "key": "FFmpegExtractAudio",
                    "preferredcodec": preferred_codec,
                    "preferredquality": "192",
                }
            ],
            "postprocessor_args": ["-ac", "1", "-ar", "16000", "-movflags", "+faststart"],
            "prefer_ffmpeg": True,
            "quiet": True,
            "no_warnings": True,
            "noplaylist": True,
        }

    async def fetch_video_info(
        self,
        *,
        url: str,
        executor: Executor | None = None,
    ) -> dict[str, Any]:
        """Fetch metadata without downloading media."""
        loop = asyncio.get_running_loop()

        def _sync() -> dict[str, Any]:
            with yt_dlp.YoutubeDL({"quiet": True, "no_warnings": True}) as ydl:
                info = ydl.extract_info(url, download=False)
            return {
                "title": info.get("title", "unknown"),
                "duration": info.get("duration"),
                "uploader": info.get("uploader"),
                "upload_date": info.get("upload_date"),
                "description": info.get("description"),
                "view_count": info.get("view_count"),
            }

        try:
            return await loop.run_in_executor(executor, _sync)
        except Exception as exc:
            raise VideoInfoError(f"Failed to fetch video info: {exc}") from exc

    async def download_audio(
        self,
        *,
        url: str,
        work_dir: Path,
        executor: Executor | None = None,
    ) -> DownloadedAudio:
        """Download and convert video audio into local file."""
        work_dir.mkdir(parents=True, exist_ok=True)
        loop = asyncio.get_running_loop()
        token = uuid4().hex[:8]
        output_template = str(work_dir / f"audio_{token}.%(ext)s")

        def _sync_download() -> tuple[Path, str, float | None]:
            ydl_opts = dict(self._base_ydl_opts)
            ydl_opts["outtmpl"] = output_template
            with yt_dlp.YoutubeDL(ydl_opts) as ydl:
                info = ydl.extract_info(url, download=False)
                ydl.download([url])
            expected = info.get("duration")
            title = info.get("title", "unknown")

            generated = work_dir / f"audio_{token}.{self._preferred_codec}"
            if generated.exists():
                return generated, title, expected

            for ext in ("m4a", "webm", "mp4", "mp3", "wav"):
                candidate = work_dir / f"audio_{token}.{ext}"
                if candidate.exists():
                    return candidate, title, expected

            raise FileNotFoundError("No downloaded audio file found")

        try:
            audio_path, video_title, expected_duration = await loop.run_in_executor(
                executor,
                _sync_download,
            )

            actual_duration = await loop.run_in_executor(
                executor,
                self._probe_duration_seconds,
                audio_path,
            )

            normalized_path = audio_path
            if self._should_normalize_duration(expected_duration, actual_duration):
                normalized_path = await loop.run_in_executor(
                    executor,
                    self._normalize_audio_duration,
                    audio_path,
                )
                actual_duration = await loop.run_in_executor(
                    executor,
                    self._probe_duration_seconds,
                    normalized_path,
                )

            return DownloadedAudio(
                audio_path=normalized_path,
                video_title=video_title,
                expected_duration_seconds=float(expected_duration) if expected_duration else None,
                actual_duration_seconds=actual_duration,
            )
        except Exception as exc:
            raise MediaDownloadError(f"Failed to download audio: {exc}") from exc

    @staticmethod
    def _probe_duration_seconds(path: Path) -> float | None:
        command = [
            "ffprobe",
            "-v",
            "error",
            "-show_entries",
            "format=duration",
            "-of",
            "default=noprint_wrappers=1:nokey=1",
            str(path),
        ]
        result = subprocess.run(command, capture_output=True, text=True, check=False)
        if result.returncode != 0:
            return None
        text = (result.stdout or "").strip()
        if not text:
            return None
        try:
            return float(text)
        except ValueError:
            return None

    @staticmethod
    def _normalize_audio_duration(path: Path) -> Path:
        normalized = path.with_name(f"{path.stem}_fixed.m4a")
        command = [
            "ffmpeg",
            "-y",
            "-i",
            str(path),
            "-vn",
            "-c:a",
            "aac",
            "-b:a",
            "160k",
            "-movflags",
            "+faststart",
            str(normalized),
        ]
        subprocess.run(command, capture_output=True, text=True, check=True)
        return normalized

    @staticmethod
    def _should_normalize_duration(expected: float | None, actual: float | None) -> bool:
        if not expected or not actual or expected <= 0:
            return False
        delta = abs(actual - expected) / expected
        return delta > 0.1

